#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export M2_HOME=/Users/David/dev/tools/maven/apache-maven-3.3.1
export PATH=$PATH:$M2_HOME/bin
export PATH=~/.local/bin:$PATH
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"


export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#Give priority to apps installed through Homebrew
export PATH=/usr/local/bin:$PATH

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh  ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
